# Numpy training with Nicholas Renotte

Numpy is fast powerful library working with arrays big and small

has support for N-dimensional arrays (arrays within arrays within arrays)

useful for deep learning libraries like tensorflow, keras, or pytorch

or performing data science with pandas or building machine learning models

pip install numpy

CRUD framework- create, read, updating, deleting

export numpy arrays to save work for later on

In [6]:
!pip install numpy

In [7]:
import numpy as np

In [1]:
# Create

array is a list that looks like this [1,2,3,4]

2 dimensional array [1,2,3,4], [5,6,7,8]

In [10]:
# 4 different types of numpy arrays
data = np.random.rand(2,3,4)     # random numbers with the shape
zeros = np.zeros ((2,2,2))
full = np.full((2,2,2),7)
ones = np.ones((2,2,2))

In [11]:
data

array([[[0.82091714, 0.16973226, 0.94940067, 0.03148648],
        [0.11951523, 0.47810289, 0.26152808, 0.83583355],
        [0.30822658, 0.18014681, 0.26174407, 0.52607911]],

       [[0.63201837, 0.43417106, 0.87767179, 0.27138301],
        [0.53501581, 0.27258162, 0.28354692, 0.92925194],
        [0.55470575, 0.18133631, 0.21966322, 0.8929564 ]]])

In [12]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [13]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [14]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

use numpy.array method for custom array

In [15]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [16]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [17]:
type(arr)

numpy.ndarray

In [4]:
# Read

In [19]:
# attributes

shape = data.shape
size = data.size
types = data.dtype

In [20]:
shape

(2, 3, 4)

In [21]:
size

24

In [22]:
types

dtype('float64')

In [25]:
# slicing through our numpy array

arr1 = data[0]     # will grab first array of 3 values from above
slicer = data[0:2]   # will grab first and second
reverse = data[-1]   # will grab last array
singlevel = data[0][0][0]  # grab a single value. first value within first dataframe 

In [24]:
arr1

array([[0.82091714, 0.16973226, 0.94940067, 0.03148648],
       [0.11951523, 0.47810289, 0.26152808, 0.83583355],
       [0.30822658, 0.18014681, 0.26174407, 0.52607911]])

In [26]:
slicer

array([[[0.82091714, 0.16973226, 0.94940067, 0.03148648],
        [0.11951523, 0.47810289, 0.26152808, 0.83583355],
        [0.30822658, 0.18014681, 0.26174407, 0.52607911]],

       [[0.63201837, 0.43417106, 0.87767179, 0.27138301],
        [0.53501581, 0.27258162, 0.28354692, 0.92925194],
        [0.55470575, 0.18133631, 0.21966322, 0.8929564 ]]])

In [3]:
# Update

In [27]:
list1 = np.random.rand(10)     #np.random.rand function
list2 = np.random.rand(10)

In [28]:
list1

array([0.00798396, 0.50270494, 0.66296314, 0.27256227, 0.48477575,
       0.08845815, 0.86414518, 0.96009581, 0.29672114, 0.95943614])

In [32]:
# Basic math functions, work on numpy arrays. with our two lists

add = np.add(list1 , list2)
sub = np.subtract(list1 , list2)
div = np.divide(list1 , list2)
mult = np.multiply(list1 , list2)
dot = np.dot(list1 , list2)     # multiply everything then aggregates together

In [31]:
add

array([0.171124  , 1.13676681, 0.75528018, 0.30762257, 0.76095596,
       0.75593771, 1.63193584, 1.79116313, 1.21595344, 1.29298973])

In [41]:
# Statiscal Functions      SAPLEMM is the acronym to remember

sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [34]:
sqrt

5.0

In [35]:
ab

2

In [36]:
power

128

In [37]:
log

3.2188758248682006

In [42]:
exp

array([ 7.3890561 , 20.08553692])

In [39]:
mins

0.007983955076324323

In [40]:
maxs

0.9600958098066945

In [44]:
data
# we want to change first value of .82091714 to 700

array([[[0.82091714, 0.16973226, 0.94940067, 0.03148648],
        [0.11951523, 0.47810289, 0.26152808, 0.83583355],
        [0.30822658, 0.18014681, 0.26174407, 0.52607911]],

       [[0.63201837, 0.43417106, 0.87767179, 0.27138301],
        [0.53501581, 0.27258162, 0.28354692, 0.92925194],
        [0.55470575, 0.18133631, 0.21966322, 0.8929564 ]]])

In [45]:
data[0][0][0] = 700

In [46]:
data

array([[[7.00000000e+02, 1.69732257e-01, 9.49400667e-01, 3.14864819e-02],
        [1.19515225e-01, 4.78102889e-01, 2.61528078e-01, 8.35833547e-01],
        [3.08226581e-01, 1.80146806e-01, 2.61744069e-01, 5.26079114e-01]],

       [[6.32018372e-01, 4.34171056e-01, 8.77671795e-01, 2.71383008e-01],
        [5.35015808e-01, 2.72581622e-01, 2.83546915e-01, 9.29251935e-01],
        [5.54705749e-01, 1.81336310e-01, 2.19663215e-01, 8.92956399e-01]]])

In [47]:
# sort function on array

data.sort()
data

array([[[3.14864819e-02, 1.69732257e-01, 9.49400667e-01, 7.00000000e+02],
        [1.19515225e-01, 2.61528078e-01, 4.78102889e-01, 8.35833547e-01],
        [1.80146806e-01, 2.61744069e-01, 3.08226581e-01, 5.26079114e-01]],

       [[2.71383008e-01, 4.34171056e-01, 6.32018372e-01, 8.77671795e-01],
        [2.72581622e-01, 2.83546915e-01, 5.35015808e-01, 9.29251935e-01],
        [1.81336310e-01, 2.19663215e-01, 5.54705749e-01, 8.92956399e-01]]])

In [48]:
print(data.shape)

(2, 3, 4)


In [ ]:
# reshape method

In [49]:
data = data.reshape((2,2,-1))

data.shape

(2, 2, 6)

In [51]:
zeros = np.zeros((8))
print(zeros)
zeros = np.append(zeros, [3,4])   # to append data to the end
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [53]:
# can insert values into the array

zeros = np.insert(zeros, 2, 1)  # add value of 1 in spot 2(0,1,2 in order of start place)
print(zeros)

[0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


In [5]:
# Delete

In [54]:
# delete a segment of an array and export our array out to use later on


In [55]:
data

array([[[3.14864819e-02, 1.69732257e-01, 9.49400667e-01, 7.00000000e+02,
         1.19515225e-01, 2.61528078e-01],
        [4.78102889e-01, 8.35833547e-01, 1.80146806e-01, 2.61744069e-01,
         3.08226581e-01, 5.26079114e-01]],

       [[2.71383008e-01, 4.34171056e-01, 6.32018372e-01, 8.77671795e-01,
         2.72581622e-01, 2.83546915e-01],
        [5.35015808e-01, 9.29251935e-01, 1.81336310e-01, 2.19663215e-01,
         5.54705749e-01, 8.92956399e-01]]])

In [56]:
# delete the first line(segments) of each array above

np.delete(data, 0, axis=1)

array([[[0.47810289, 0.83583355, 0.18014681, 0.26174407, 0.30822658,
         0.52607911]],

       [[0.53501581, 0.92925194, 0.18133631, 0.21966322, 0.55470575,
         0.8929564 ]]])

In [58]:
# save our array. save in directory of jupyter notebook

# np.save("new array", data)

# saves to directory

# test = np.load("new array.npy")

# test      - will reload it from memory